// libraries/vue-main/src/components/DevApp/ServiceDock.vue
<template>
  <div>{{ text }}</div>
  <div>{{ workingDirectory }}</div>
  <div>{{ delimiter }}</div>
  <FileExplorer :base-path="basePath" :height="450" />
</template>

<script setup lang="ts">
import { ref } from "vue";
import { storeToRefs } from "pinia";
import { useDeployStore } from "../../stores/devStore";
import FileExplorer from "../File/FileExplorer.vue";

const props = defineProps<{
  system?: Record<string, any>;
}>();

const deploy = useDeployStore();

const { workingDirectory, delimiter } = storeToRefs(deploy);

const basePath = ref(`${workingDirectory.value}${delimiter.value}${props.system?.SYSTEM_ID}`);
const text: string = `${props.system?.SYSTEM_ID}:service`;
</script>

// libraries/react-main/src/components/DevApp/ServiceDock.tsx
import * as React from "react";
import { useRecoilValue } from "recoil";
import { getWorkingDirectory, getServerDelimiter } from "../../stores/devStore";
import FileExplorer from "../File/FileExplorer";

interface IServiceProps {
  system?: Record<string, any>;
}

const ServiceDock: React.FC<IServiceProps> = props => {
  const workingDirectory = useRecoilValue(getWorkingDirectory);
  const delimiter = useRecoilValue(getServerDelimiter);

  return (
    <>
      <div>{props.system?.SYSTEM_ID}</div>
      <div>{workingDirectory}</div>
      <div>{delimiter}</div>
      <FileExplorer basePath={`${workingDirectory}${delimiter}${props.system?.SYSTEM_ID}`} height={450} />
    </>
  );
};

export default React.memo(ServiceDock);
