// libraries/react-component/src/Splitter/Splitter.tsx
import * as React from "react";
import ReactDOM from "react-dom/client";
import {
  Splitter as SplitterComponent,
  Pane as PaneComponent,
  ISplitterProps,
  Direction,
  createCamelProps,
} from "@aleatorik-ui/common-ui";

interface ISplitterPropsDetail extends ISplitterProps {
  children?: React.ReactNode | React.ReactNode[];
  renderPane?: (child: any, parent: HTMLElement) => void;
}

const Splitter: React.FC<ISplitterPropsDetail> = props => {
  const splitterRef = React.useRef(null);

  React.useEffect(() => {
    const contents: PaneComponent[] = [];
    const addPane = (child: any) => {
      contents.push(
        new PaneComponent({
          contents: (parents: HTMLElement) => {
            if (props.renderPane) {
              props.renderPane(child, parents);
            } else {
              ReactDOM.createRoot(parents).render(child);
            }
          },
          direction: props.direction,
          resizersSize: props.resizerSize,
          size: child.props["pane-size"],
          minSize: child.props["pane-min-size"],
          maxSize: child.props["pane-max-size"],
        }),
      );
    };
    if (props.children && Array.isArray(props.children)) {
      props.children.forEach((child: any) => {
        addPane(child);
      });
    } else {
      addPane(props.children);
    }
    const splitter = new SplitterComponent({
      parents: splitterRef.current as unknown as HTMLElement,
      ...createCamelProps<ISplitterProps>(props),
      contents,
    });
    splitter.render();

    return () => {
      splitter.dispose();
    };
  });
  return (
    <>
      <div className="moz-splitter-root" ref={splitterRef}></div>
    </>
  );
};

export default Splitter;

// libraries/vue-component-wijmo/src/Splitter/Splitter.vue
<template>
  <div class="moz-splitter-root" ref="splitterRef"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, useSlots, Comment, render, watch, defineExpose } from "vue";
import {
  Splitter as SplitterComponent,
  Pane as PaneComponent,
  ISplitterProps,
  Direction,
  createCamelProps,
} from "@aleatorik-ui/common-ui";

const props = defineProps<{
  direction?: Direction;
  resizerSize?: Number;
  onResizeStart?: () => void;
  onResizeEnd?: (sizes: string[]) => void;
  onChange?: (sizes: string[]) => void;
  allowResize?: Boolean;
  classList?: string[];
  style?: object;
  changed?: Boolean;
  renderPane?: (child: any, parent: HTMLElement) => void;
}>();

const splitterRef = ref(null);
const splitter = ref(null as SplitterComponent | null);

const slots = useSlots();
const defaultSlots = (slots.default as any)();

const renderChildren = () => {
  const contents: PaneComponent[] = [];
  defaultSlots
    .filter((slot: any) => slot.type !== Comment)
    .forEach((slot: any) => {
      contents.push(
        new PaneComponent({
          contents: (parents: HTMLElement) => {
            if (props.renderPane) {
              props.renderPane(slot, parents);
            } else {
              render(slot, parents);
            }
          },
          direction: props.direction,
          resizersSize: props.resizerSize as number | undefined,
          size: slot.props ? slot.props["pane-size"] : undefined,
          minSize: slot.props ? slot.props["pane-min-size"] : undefined,
          maxSize: slot.props ? slot.props["pane-max-size"] : undefined,
        }),
      );
    });
  splitter.value = new SplitterComponent({
    parents: splitterRef.value as unknown as HTMLElement,
    ...createCamelProps<ISplitterProps>(props),
    contents,
  });
  splitter.value.render();
};

onMounted(renderChildren);

watch(props, () => {
  renderChildren();
});

onUnmounted(() => {
  if (!splitter || !splitter.value) return;
  splitter.value.dispose();
});

defineExpose({
  splitterRef,
  splitter,
});
</script>
