// packages/standard/src/components/UserApp/MenuList.vue
<template>
  <div
    :class="{
      'moz-topleft-trigger-area': true,
      open: drawer,
    }"
  >
    <div :class="{ 'moz-left-closer': drawer }" @click="onClickLeftHider">
      <i class="mozart-icons left-arrow"></i>
    </div>
  </div>
  <div v-show="drawer">
    <div class="root-menu">
      <span v-if="!secondMenu">{{ rootMenu?.name }}</span>
      <span v-if="secondMenu">{{ secondMenu?.name }}</span>
    </div>
    <Tree
      :class="{ 'dx-left-drawer-treeview': true, 'closed-node': !drawer }"
      ref="dxListView"
      :items="[
        ...getMenuSetting.map(menu => {
          return {
            id: menu.menuId,
            parentId: menu.categoryId,
            expanded: menu.type === 'Category' ? true : false,
            name: menu.name,
            path: menu.path,
            type: menu.type,
          };
        }),
      ]"
      :root-value="menuLocation === 'topandleft' ? targetId : rootMenuId"
      mode="plat"
      class="moz-side-menu"
      :onItemClick="onItemClick"
    >
    </Tree>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from "vue";
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { useLayoutStore, useMenuItems, useMenuStore, useMenuLocationStore, IMenu } from "../../stores/mainStore";
import { Tree } from "@aleatorik-ui/vue-component-wijmo";
import { showConfirm } from "../../utils/dialog";

const layout = useLayoutStore();
const { drawer } = storeToRefs(layout);

const menuItemsStore = useMenuItems();
const { getMenuSetting } = storeToRefs(menuItemsStore);

const menuModule = useMenuStore();
const { targetId, rootMenuId, currentMenu, rootMenu, secondMenu, isEditing } = storeToRefs(menuModule);

const menuLocationStore = useMenuLocationStore();
const { menuLocation } = storeToRefs(menuLocationStore);

const router = useRouter();

const dxListView = ref(null);

watch(currentMenu, () => {
  nextTick(() => {
    const tree = (dxListView.value as any).tree;
    tree.selectNode(currentMenu.value?.menuId, tree.element);
  });
});

const redirectMenu = async (menu?: IMenu, params?: Record<string, any>) => {
  if (!menu) return;
  if (menu.type === "Category") return;
  if (!menu.path) return;

  if (isEditing.value) {
    const result = await showConfirm({
      title: `Cancel`,
      message: `Are you sure you want to <b>Leave</b> this page?`,
    });
    if (!result) return;
    menuModule.endEdit();
  }

  router.push({
    path: menu.path,
    params: {
      ...params,
    },
  });
};

const onItemClick = async (e: any) => {
  if (e.itemData.type === "Category") return;

  let obj = e.itemData;

  if (!obj.menuId) {
    obj = {
      menuId: obj.id,
      name: obj.name,
      categoryId: obj.parentId,
      type: obj.type,
      path: obj.path,
    };
  }

  menuModule.setCurrentMenu(obj);
  redirectMenu(obj);
};

// const onHover = (e: any, item: any) => {
//   if (!drawer) {
//     let target = e.target;
//     if (e.target.nodeName === "I") target = e.target.parentElement;
//     addTooltipEvent(target, item.name as string, false, "elright");
//   }
// };

// const onMouseOut = (e: any) => {
//   if (!drawer) {
//     let target = e.target;
//     if (e.target.nodeName === "I") target = e.target.parentElement;
//     target.onmouseenter = undefined;
//   }
// };

// const onMenuItemOver = (evt: MouseEvent) => {
//   const el = evt.target as HTMLElement;
//   if (el.offsetWidth < el.scrollWidth) {
//     addTooltipEvent(el, el.innerText, false, "elright");
//   }
// };

// const onMenuItemOut = (evt: MouseEvent) => {
//   const ts = document.getElementsByClassName("tooltip");
//   if (ts && ts.length > 0) {
//     Array.from(ts).forEach(t => {
//       document.body.removeChild(t);
//     });
//   }
// };

const onClickLeftHider = (e: any) => {
  // const el = e.target as HTMLElement;
  // el.classList.add("close-left-drawer");
  // el.classList.remove("left-arrow");
  layout.setLayout({
    ...storeToRefs(layout),
    drawer: false,
  });
};

// const onToggleLeftDrawer = (e: any) => {
//   layout.setLayout({
//     ...storeToRefs(layout),
//     drawer: true,
//   });
//   const { option } = e.detail.params;
//   option.drawer = drawer;
// };

// const onGetDrawerState = (e: any) => {
//   const { option } = e.detail.params;
//   option.drawer = drawer;
//   option.menuLocation = menuLocation;
//   console.log(option);
// };
</script>

// libraries/react-main/src/components/UserApp/MenuList.tsx
import React from "react";
import { useNavigate } from "react-router-dom";
import { useRecoilValue } from "recoil";
import { TreeView } from "devextreme-react/ui/tree-view";
import { addTooltipEvent } from "@aleatorik-ui/common-ui";
import { menus, IMenu } from "@aleatorik-ui/common-api";
import { layoutState } from "../../stores/mainStore";

const MenuList: React.FC = () => {
  const layout = useRecoilValue(layoutState);
  const navigate = useNavigate();

  const redirectMenu = (menu?: IMenu, params?: Record<string, any>) => {
    if (!menu) return;
    if (menu.categoryId === "Category") return;
    if (!menu.path) return;
    navigate(menu.path);
    // pushRoute(this.$router, menu.URL, params);
  };

  const onInit = async () => {
    // await this.treemenu.selectItem(MainModule.currentMenuId);
    // await this.treemenu.expandItem(MainModule.currentCategoryId);
    // await this.treemenu.expandItem(MainModule.currentMenuId);
    // await this.onMenuChanged({});
  };

  const onItemClick = async (e: any) => {
    // if (currentMenu === e.itemData.menuId) return;
    // if (!drawer) MainModule.toggle();
    // else {
    // if (MenuModule.getIsChanging) {
    //   const result = await confirm("Are you sure you want to <b>Leave</b> this page?", "Cancel");
    //   if (!result) return;
    // }
    // MenuModule.setIsChanging(false);
    // if (MenuModule.getIsChanging) return;
    // remainFocusIfClickedSameNode(e);
    if (e.itemData.type === "Category") return;
    // MenuModule.setRootMenu(this.findParentItem(e));
    // MenuModule.setSecondMenu(this.findSecondItem(e));

    // await this.treemenu.selectItem(e.itemData.MENU_ID);

    redirectMenu(e.itemData);
    const pointerEvent = e.event;
    pointerEvent.stopPropagation();
    // }
  };

  const onHover = (e: any, item: any) => {
    if (!layout.drawer) {
      let target = e.target;
      if (e.target.nodeName === "I") target = e.target.parentElement;
      addTooltipEvent(target, item.name as string, false, "elright");
    }
  };

  const onMouseOut = (e: any) => {
    if (!layout.drawer) {
      let target = e.target;
      if (e.target.nodeName === "I") target = e.target.parentElement;
      target.onmouseenter = undefined;
    }
  };

  const onMenuItemOver = (evt: React.MouseEvent) => {
    const el = evt.target as HTMLElement;
    if (el.offsetWidth < el.scrollWidth) {
      addTooltipEvent(el, el.innerText, false, "elright");
    }
  };
  const onMenuItemOut = (evt: React.MouseEvent) => {
    const ts = document.getElementsByClassName("tooltip");
    if (ts && ts.length > 0) {
      Array.from(ts).forEach(t => {
        document.body.removeChild(t);
      });
    }
  };
  const renderItem = (data: IMenu) => {
    const MenuText = () => {
      if (layout.drawer) {
        return (
          <span onMouseOver={onMenuItemOver} onMouseOut={onMenuItemOut}>
            {data.name}
          </span>
        );
      } else {
        return <></>;
      }
    };
    const MenuItem = () => {
      if (data.type === "Category" && !data.categoryId) {
        return (
          <div className="first-node">
            <i className="mozart-icons m-017_menuitem"></i>
            <MenuText />
          </div>
        );
      } else if (data.type === "Category" && data.categoryId) {
        return (
          <div className="second-node">
            <MenuText />
          </div>
        );
      } else {
        return (
          <div className="child-node">
            <MenuText />
          </div>
        );
      }
    };
    return (
      <div onMouseOver={evt => onHover(evt, data)} onMouseOut={onMouseOut}>
        <div>
          <MenuItem />
        </div>
      </div>
    );
  };

  return (
    <TreeView
      id="menu"
      className={`moz-drawer-treeview ${layout.drawer ? "" : "closed-node"}`}
      items={menus}
      selection-mode="single"
      dataStructure="plain"
      keyExpr="menuId"
      parentIdExpr="categoryId"
      displayExpr="name"
      expandedExpr="expanded"
      rootValue=""
      hoverStateEnabled={true}
      focusStateEnabled={false}
      expandEvent="click"
      onInitialized={onInit}
      onItemClick={onItemClick}
      width="100%"
      itemRender={renderItem}
    />
  );
};

export default MenuList;
