// packages/standard/src/views/Modeler.vue
<template>
  <div class="moz-frame-no-control">
    <!-- <Modeler :style-object="{ height: 'var(--size-content-inner-height-no-padding)' }"></Modeler> -->
  </div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import { GetModel } from "@aleatorik-ui/common-api";
// import { Modeler } from "@aleatorik-ui/vue-component-wijmo";

onMounted(async () => {
  const result = await GetModel();
  if (result && result.data) {
    console.log(result.data);
  }
});
</script>

// templates/react-template/src/views/Modeler.tsx
import * as React from "react";
import { GetModel } from "@mozart-ui/common-api";
// import { Modeler as ModelerComponent } from "@mozart-ui/react-component";

const Modeler: React.FC = () => {
  React.useEffect(() => {
    (async () => {
      const result = await GetModel();
      if (result && result.data) {
        console.log(result.data);
      }
    })();
  }, []);

  return (
    <div className="moz-frame-no-control">
      {/* <ModelerComponent
        styleObject={{ height: "var(--size-content-inner-height-no-padding)" }}
      ></ModelerComponent> */}
    </div>
  );
};

export default Modeler;
