// libraries/react-component/src/Graph/Graph.tsx
import * as React from "react";
import { Graph as GanttComponent, IGraphProps } from "@mozart-ui/common-ui";

const Graph: React.FC<IGraphProps> = (props: IGraphProps) => {
  const graphRef = React.useRef(null);

  React.useEffect(() => {
    const gantt = new GanttComponent({
      parents: graphRef.current as unknown as HTMLElement,
      ...props,
    });
    gantt.render();

    return () => {
      gantt.dispose();
    };
  });
  return (
    <>
      <div ref={graphRef} className="moz-graph-root"></div>
    </>
  );
};

export default Graph;

// libraries/vue-component-wijmo/src/Graph/Graph.vue
<template>
  <div ref="graphRef" className="moz-graph-root"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, defineExpose } from "vue";
import { Graph as GraphComponent, ElementDefinition, ElementsDefinition } from "@mozart-ui/common-ui";
import { IGraphProps, createCamelProps } from "@mozart-ui/common-ui";

const props = defineProps<{
  elements?: ElementsDefinition | ElementDefinition[] | Promise<ElementsDefinition> | Promise<ElementDefinition[]>;
  styleObj?: Array<Record<string, any>> | Promise<Array<Record<string, any>>>;
  layout?: Record<string, any>;
  option?: Record<string, any>;
  navigator?: Record<string, any>;
  undoRedo?: Record<string, any>;
  utilities?: Record<string, any>;
  contextMenu?: Record<string, any>;
}>();

const graphRef = ref(null);
const graph = ref(null as GraphComponent | null);

onMounted(() => {
  graph.value = new GraphComponent({
    parents: graphRef.value as unknown as HTMLElement,
    ...createCamelProps<IGraphProps>(props),
  });
  graph.value.render();
});

onUnmounted(() => {
  if (!graph || !graph.value) return;
  graph.value.dispose();
});

defineExpose({
  graphRef,
  graph,
});
</script>
