// libraries/vue-main/src/components/DevApp/Sql/SqlResults.vue
<template>
  <DxDataGrid
    class="moz-edit-datagrid"
    width="100%"
    height="100%"
    :data-source="props.results"
    :allow-column-reordering="true"
    :allow-column-resizing="true"
    :column-auto-width="true"
    column-resizing-mode="widget"
    :auto-navigate-to-focused-row="false"
    :show-borders="false"
    :show-column-lines="false"
    :selection="{ mode: 'single' }"
    :hover-state-enabled="true"
    no-data-text="No data to display"
  >
  </DxDataGrid>
</template>

<script setup lang="ts">
import { DxDataGrid, DxColumn } from "devextreme-vue/data-grid";

const props = defineProps<{
  results?: any[];
}>();
</script>

// libraries/react-main/src/components/DevApp/Sql/SqlResults.tsx
import * as React from "react";
import { DataGrid, Column } from "devextreme-react/data-grid";

interface IDataItemProp {
  results?: any[];
}

const SqlResults: React.FC<IDataItemProp> = props => {
  return (
    <>
      <DataGrid
        className="moz-edit-datagrid"
        width="100%"
        height="100%"
        dataSource={props.results}
        allowColumnReordering={true}
        allowColumnResizing={true}
        columnAutoWidth={true}
        columnResizingMode="widget"
        keyExpr="name"
        autoNavigateToFocusedRow={false}
        showBorders={false}
        showColumnLines={false}
        selection={{ mode: "single" }}
        hoverStateEnabled={true}
        noDataText="No data to display"
      >
      </DataGrid>
    </>
  );
};

export default React.memo(SqlResults);
