// templates/vue-template/src/views/UserApp.vue
<template>
  <dx-drawer
    v-if="login"
    class="moz-drawer"
    :minSize="DRAWER_MIN"
    :maxSize="DRAWER_MAX"
    :opened="drawer"
    opened-state-mode="push"
    reveal-mode="slide"
    template="drawer-content"
  >
    <template #drawer-content>
      <div className="moz-side-menu">
        <div className="side-top-area">
          <div className="toggle-menu">
            <i className="mozart-icons m-016_menu" @click="onToggleClick()" />
          </div>
          <div v-if="drawer" className="drawer-logo-area" @click="onClickLogo">Logo</div>
        </div>
        <MenuList></MenuList>
      </div>
    </template>
    <div id="content" className="moz-contents">
      <TopAppBar class="moz-top-bar" ref="top" />
      <router-view></router-view>
    </div>
  </dx-drawer>
</template>

<script setup lang="ts">
import { storeToRefs } from "pinia";
import DxDrawer from "devextreme-vue/drawer";
import { DRAWER_MAX, DRAWER_MIN } from "@mozart-ui/common-ui";

import { useLayoutStore, TopAppBar, MenuList } from "@mozart-ui/vue-main";

const layout = useLayoutStore();
const { login, drawer } = storeToRefs(layout);

const onToggleClick = () => {
  layout.setLayout({
    ...storeToRefs(layout),
    drawer: !layout.drawer,
  });
};

const onClickLogo = () => {
  console.log("logo");
};
</script>

// libraries/react-main/src/views/UserApp.tsx
import React from "react";
import Routes from "../router/user";
import { useRecoilState } from "recoil";
import Drawer from "devextreme-react/drawer";
import { DRAWER_MAX, DRAWER_MIN } from "@mozart-ui/common-ui";

import { layoutState } from "../stores/mainStore";

import TopAppBar from "../components/UserApp/TopAppBar";
import MenuList from "../components/UserApp/MenuList";

const UserApp: React.FC = () => {
  const [layout, setLayout] = useRecoilState(layoutState);
  const onToggleClick = () => {
    setLayout(oldVal => ({
      ...oldVal,
      drawer: !oldVal.drawer,
    }));
  };
  const onClickLogo = () => {
    console.log("logo");
  };
  const Title = () => {
    if (layout.drawer) {
      return (
        <div className="drawer-logo-area" onClick={onClickLogo}>
          Logo
        </div>
      );
    } else {
      return <template></template>;
    }
  };
  const DrawerContent = () => {
    return (
      <div className="moz-side-menu">
        <div className="side-top-area">
          <div className="toggle-menu">
            <i className="mozart-icons m-016_menu" onClick={onToggleClick} />
          </div>
          <Title></Title>
        </div>
        <MenuList></MenuList>
      </div>
    );
  };
  return (
    <Drawer
      className="moz-drawer"
      minSize={DRAWER_MIN}
      maxSize={DRAWER_MAX}
      opened={layout.drawer}
      openedStateMode="push"
      revealMode="slide"
      render={DrawerContent}
    >
      <div id="content" className="moz-contents">
        <TopAppBar />
        <Routes />
      </div>
    </Drawer>
  );
};

export default UserApp;
