// libraries/react-main/src/views/Login.tsx
import React, { useState } from "react";
import { useSetRecoilState } from "recoil";
import { useMutation } from "react-query";
import { useTranslation } from "react-i18next";
import Button from "devextreme-react/button";
import TextBox from "devextreme-react/text-box";
import { Validator, RequiredRule, PatternRule, StringLengthRule } from "devextreme-react/validator";
import { CheckBox } from "devextreme-react/check-box";

import { Login as LoginCall, getCookie, setCookie, parseExpires, removeCookie } from "@aleatorik-ui/common-api";
import { encodeUnescapeBtoa, decodeEscapeAtob } from "@aleatorik-ui/common-ui";
import { layoutState, loadState, alarmState, userState } from "../stores/mainStore";

const Login: React.FC = () => {
  const { t } = useTranslation();
  const [id, setId] = useState(decodeEscapeAtob(getCookie("save_id")));
  const [password, setPassword] = useState("");
  const [saveId, setSaveId] = useState(id ? true : false);
  const setLayout = useSetRecoilState(layoutState);
  const setLoad = useSetRecoilState(loadState);
  const setAlarm = useSetRecoilState(alarmState);
  const setUser = useSetRecoilState(userState);
  const failedLogin = (message: string) => {
    setAlarm(() => ({
      message,
      type: "error",
    }));
  };

  const mutation = useMutation(LoginCall, {
    onSuccess: result => {
      if (result && result.data && result.data.success) {
        setCookie("refresh_token", encodeUnescapeBtoa(result.data.refreshToken), {
          sameSite: "strict",
          expires: parseExpires(result.data.expiration),
        });
        if (saveId) {
          setCookie("save_id", encodeUnescapeBtoa(id), { sameSite: "strict" });
        } else {
          removeCookie("save_id");
        }
        setLayout(oldVal => ({
          ...oldVal,
          login: true,
        }));
        setUser(() => ({
          name: result.data.userName,
          email: result.data.email,
          role: result.data.role,
        }));
      } else {
        failedLogin("SignIn Failed!");
      }
      setLoad({ loading: false });
    },
    onError: (err: any) => {
      setLoad({ loading: false });
      failedLogin(err.message);
    },
  });

  const onLogin = async () => {
    if (!id || !password) return;
    setLoad({ loading: true });
    mutation.mutate({ userName: id, password });
  };

  return (
    <div className="moz-login">
      <div className="moz-login-title">Login</div>
      <TextBox value={id} placeholder="UserName" onValueChange={setId} onEnterKey={onLogin}>
        <Validator>
          <RequiredRule />
          <PatternRule pattern={/^[a-zA-Z0-9]+$/} message={"`${'UserName'} must be a english and number.`"} />
        </Validator>
      </TextBox>
      <TextBox value={password} mode="password" placeholder="Password" onValueChange={setPassword} onEnterKey={onLogin}>
        <Validator>
          <RequiredRule />
          <StringLengthRule min={4} />
        </Validator>
      </TextBox>
      <Button
        className="moz-button-login"
        type="default"
        stylingMode="contained"
        useSubmitBehavior={true}
        text={t("Login") as string}
        width={430}
        height={65}
        onClick={onLogin}
      ></Button>
      <div className="moz-login-control">
        <div>
          <CheckBox value={saveId} text={t("SaveID") as string} width={100} onValueChange={setSaveId} />
        </div>
        {/* <div style="vertical-align: top">
        <a :href="`mailto:${adminEamil}`" className="moz-link">{{ "request_admin" }}</a>
      </div> */}
      </div>
    </div>
  );
};

export default Login;

// libraries/vue-main/src/views/Login.vue
<template>
  <div className="moz-login">
    <div className="moz-login-title">Login</div>
    <dx-text-box v-model:value="compId" placeholder="UserName" @enter-key="onLogin">
      <dx-validator>
        <dx-required-rule />
        <dx-pattern-rule :pattern="/^[a-zA-Z0-9]+$/" :message="`${'UserName'} must be a english and number.`" />
      </dx-validator>
    </dx-text-box>
    <dx-text-box v-model:value="compPass" mode="password" placeholder="Password" @enter-key="onLogin">
      <dx-validator>
        <dx-required-rule />
        <dx-string-length-rule :min="4" />
      </dx-validator>
    </dx-text-box>
    <dx-button
      class="moz-button-login"
      type="default"
      styling-mode="contained"
      :use-submit-behavior="true"
      :text="t('Login')"
      :width="430"
      :height="65"
      @click="onLogin"
    >
    </dx-button>
    <div className="moz-login-control">
      <div style="margin: auto 0px">
        <dx-check-box v-model:value="compSaveId" :text="t('SaveID')" :width="100" />
      </div>
      <!-- <div style="vertical-align: top">
        <a :href="`mailto:${adminEamil}`" className="moz-link">{{ "request_admin" }}</a>
      </div> -->
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { storeToRefs } from "pinia";
import { useMutation } from "vue-query";
import { useTranslation } from "i18next-vue";
import DxButton from "devextreme-vue/button";
import DxTextBox from "devextreme-vue/text-box";
import { DxValidator, DxRequiredRule, DxPatternRule, DxStringLengthRule } from "devextreme-vue/validator";
import { DxCheckBox } from "devextreme-vue/check-box";

import { Login as LoginCall, getCookie, setCookie, parseExpires, removeCookie } from "@aleatorik-ui/common-api";
import { encodeUnescapeBtoa, decodeEscapeAtob } from "@aleatorik-ui/common-ui";
import { useLayoutStore, useLoadStore, useAlarmStore, useUserStore } from "../stores/mainStore";

const { t } = useTranslation();

const layout = useLayoutStore();
const load = useLoadStore();
const alarm = useAlarmStore();
const user = useUserStore();

const savedId = ref(decodeEscapeAtob(getCookie("save_id")));
let id = savedId.value;
let pw = "";
let saveId = savedId.value ? true : false;

const failedLogin = (message: string) => {
  alarm.setAlarm({
    message,
    type: "error",
  });
};

const mutation = useMutation(LoginCall, {
  onSuccess: result => {
    if (result && result.data && result.data.success) {
      setCookie("refresh_token", encodeUnescapeBtoa(result.data.refreshToken), {
        sameSite: "strict",
        expires: parseExpires(result.data.expiration),
      });
      if (saveId) {
        setCookie("save_id", encodeUnescapeBtoa(id), { sameSite: "strict" });
      } else {
        removeCookie("save_id");
      }
      user.setUser({
        name: result.data.userName,
        email: result.data.email,
        role: result.data.role,
      });
      layout.setLayout({
        ...storeToRefs(layout),
        login: true,
      });
    } else {
      failedLogin("SignIn Failed!");
    }
    load.setLoad({ loading: false });
  },
  onError: (err: any) => {
    failedLogin(err.message);
    load.setLoad({ loading: false });
  },
});

const onLogin = async () => {
  if (!id || !pw) return;
  load.setLoad({ loading: true });
  mutation.mutate({ userName: id, password: pw });
};

const compId = computed({
  get: () => id,
  set: val => (id = val),
});
const compPass = computed({
  get: () => pw,
  set: val => (pw = val),
});
const compSaveId = computed({
  get: () => saveId,
  set: val => (saveId = val),
});
</script>
