// libraries/vue-component/src/Gauge/Gauge.vue
<template>
  <div class="moz-gauge-root" ref="gaugeRef"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, useSlots, watch, getCurrentInstance, defineExpose } from "vue";
import {
  Gauge as GaugeComponent,
  Bar as BarComponent,
  Arc as ArcComponent,
  Mark as MarkComponent,
  IGaugeProps,
  IBarProps,
  IArcProps,
  IMarkProps,
  GaugeType,
  createCamelProps,
  IGaugeTooltipParams,
} from "@mozart-ui/common-ui";

const props = defineProps<{
  width: Number;
  height: Number;
  type?: GaugeType;
  minValue?: Number;
  maxValue?: Number;
  backColor?: String;
  verticalPosition?: Number;
  innerRadius?: Number;
  outerRadius?: Number;
  cornerRadius?: Number;
  startAngle?: Number;
  endAngle?: Number;
  reverse?: Boolean;
  colorHash?: Record<string, any>;
  noDataText?: String;
  showTooltip?: Boolean;
  setToolTip?: (params: IGaugeTooltipParams) => string;
}>();

const gaugeRef = ref(null);
const gauge = ref(null as GaugeComponent | null);

const slots = useSlots();

const renderGauge = () => {
  const bars: BarComponent[] = [];
  const arcs: ArcComponent[] = [];
  const marks: MarkComponent[] = [];
  const defaultSlots = (slots.default as any)();
  defaultSlots
    .filter((slot: any) => slot.type && slot.type.__file)
    .forEach((slot: any) => {
      if (slot.type.__file.endsWith("Bar.vue")) {
        bars.push(new BarComponent(createCamelProps<IBarProps>(slot.props)));
      } else if (slot.type.__file.endsWith("Arc.vue")) {
        arcs.push(new ArcComponent(createCamelProps<IArcProps>(slot.props)));
      } else if (slot.type.__file.endsWith("Mark.vue")) {
        marks.push(new MarkComponent(createCamelProps<IMarkProps>(slot.props)));
      }
    });
  gauge.value = new GaugeComponent({
    parents: gaugeRef.value as unknown as HTMLElement,
    ...createCamelProps<IGaugeProps>(props),
    bars,
    arcs,
    marks,
  });
  gauge.value.render();
};

onMounted(renderGauge);

onUnmounted(() => {
  if (!gauge || !gauge.value) return;
  gauge.value.dispose();
});

watch(slots.default as any, renderGauge);

defineExpose({
  gaugeRef,
  gauge,
});
</script>

// libraries/react-component/src/Gauge/Gauge.tsx
import * as React from "react";
import {
  Gauge as GaugeComponent,
  Bar as BarComponent,
  Arc as ArcComponent,
  Mark as MarkComponent,
  IGaugeProps,
  IBarProps,
  IArcProps,
  IMarkProps,
  createCamelProps,
} from "@mozart-ui/common-ui";

interface IGaugePropsDetail extends IGaugeProps {
  children?: React.ReactNode | React.ReactNode[];
}

const Gauge: React.FC<IGaugePropsDetail> = props => {
  const gaugeRef = React.useRef(null);

  React.useEffect(() => {
    const bars: BarComponent[] = [];
    const arcs: ArcComponent[] = [];
    const marks: MarkComponent[] = [];
    if (props.children) {
      const children: React.ReactNode[] = [];
      if (Array.isArray(props.children)) {
        children.push(...props.children);
      } else {
        children.push(props.children);
      }
      children.forEach((child: any) => {
        if (child.type.name === "Bar") {
          bars.push(new BarComponent(createCamelProps<IBarProps>(child.props)));
        } else if (child.type.name === "Arc") {
          arcs.push(new ArcComponent(createCamelProps<IArcProps>(child.props)));
        } else if (child.type.name === "Mark") {
          marks.push(new MarkComponent(createCamelProps<IMarkProps>(child.props)));
        }
      });
    }
    const gauge = new GaugeComponent({
      parents: gaugeRef.current as unknown as HTMLElement,
      ...createCamelProps<IGaugeProps>(props),
      bars,
      arcs,
      marks,
    });
    gauge.render();

    return () => {
      gauge.dispose();
    };
  });
  return (
    <>
      <div className="moz-gauge-root" ref={gaugeRef}></div>
    </>
  );
};

export default Gauge;
