// templates/vue3-template/src/components/Loader.vue
<template>
  <DxLoadPanel
    v-model:visible="loading"
    :show-indicator="true"
    :show-pane="true"
    :shading="true"
    shading-color="rgba(0,0,0,0.4)"
  />
</template>

<script setup lang="ts">
import { storeToRefs } from "pinia";
import { DxLoadPanel } from "devextreme-vue/load-panel";
import { useLoadStore } from "../stores/mainStore";

const load = useLoadStore();
const { loading } = storeToRefs(load);
</script>

// libraries/react-main/src/components/Loader.tsx
import * as React from "react";
import { useRecoilValue } from "recoil";
import { LoadPanel } from "devextreme-react/load-panel";
import { loadState } from "../stores/mainStore";

const Home: React.FC = () => {
  const load = useRecoilValue(loadState);
  return (
    <LoadPanel
      visible={load.loading}
      showIndicator={true}
      shading={true}
      showPane={true}
      shadingColor="rgba(0,0,0,0.4)"
    />
  );
};

export default Home;
